apiVersion: sts.silicom.com/v1alpha1
kind: StsConfig
metadata:
  name: bc-1
  namespace: openshift-operators
spec:
  nodeSelector:
    sts.silicom.com/config: "bc-1"
  mode: T-BC-8275.1
  interfaces:
    - ethName: enp2s0f0
      synce: 1
      holdoff: 500
      mode: Slave
      ethPort: 1
      ql: 4
      qlEnable: 1
      ipv4: 1
      ipv6: 1
    - ethName: enp2s0f1
      synce: 1
      holdoff: 500
      ethPort: 1
      mode: Master
      ql: 4
      qlEnable: 1
      ipv4: 1
      ipv6: 1
    - ethName: enp2s0f2
      synce: 1
      holdoff: 500
      ethPort: 2
      mode: Master
      ql: 4
      qlEnable: 1
      ipv4: 1