apiVersion: sts.silicom.com/v1alpha1
kind: StsConfig
metadata:
  name: gm-1
spec:
  nodeSelector:
    sts.silicom.com/config: "gm-1"
  mode: T-GM.8275.1
  interfaces:
    - ethName: enp2s0f0
      synce: 1
      holdoff: 500
      mode: Master
      ethPort: 1
      ql: 4
      qlEnable: 1
      ipv4: 1
      ipv6: 1
